### ISSUE TITLE
Why are negative coordinates disallowed in BBox2D setters?

### ISSUE THREAD

**Issue by gmyers18** [varunagrawal/bbox#10]
Thanks for putting this library together -- we are finding it very useful.

One limitation we have encountered is that the various setters for the x/y coordinates in BBox2D raise an exception when faced with negative values.  It is not clear why this limitation is in place, and it also seems a little inconsistent since the constructor does allow for instantiating a bbox with negative coordinates.

Additionally, the width and height setters prohibit negative values which seems sensible, but there is not similar checking in the constructor and thus you can instantiate a bbox with negative width/height.

**Comment by varunagrawal** [comment]
Ah good catches. It doesn't make sense to have negative values for x/y values (or does it?) since you would want to clamp that to `[0, H/W)` for it to be meaningful for any object detection system.

I can definitely fix the constructor to put in the required checks though. Would you have any thoughts on whether allowing negative x/y values would make sense?

**Comment by varunagrawal** [comment]
Also, word of caution, currently the way I compute x2 is `x2 = x1+w-1`, but after talking to detection experts, they all agree that the 1-offset should be a non-artifact and x2 should be computed as `x2  = x1 + w`.

I am going to thus change the API behavior in the near future (hence why this project is still in beta!) and publish a v1 once I see things follow the modern practices regarding bounding boxes.

**Comment by gmyers18** [comment]
From my perspective allowing negative coordinates will allow the library to be more flexible as a means for generically describing a region of interest with a bounding box.

I think the need to clip to scene/image bounds is a very common use case with bounding boxes, but it is ultimately application dependent.  But other applications might be interested in maintaining state for regions that are fully or partially out of scene, where there is information that you don't want to lose in the fact that something is (partially) out of scene.  The application itself would then need to handle any sort of clipping downstream if it needs things to be fully in-bounds for visualization, etc.

**Comment by gmyers18** [comment]
Thanks for the head's up.  I think the -1 offset is a fairly common point of disagreement when it comes to bounding boxes.  FWIW I think the way you have it currently with the -1 is correct, but I have certainly seen it the other way too.

**Comment by varunagrawal** [comment]
I can't argue against your point for negative values. Thank you for the feedback, since this will definitely make bbox more flexible.

**Comment by varunagrawal** [comment]
I have updated the package to allow `BBox2D` to accept negative values. New version is 0.9.1.

**Comment by gmyers18** [comment]
Looks great.  Thanks!
