### ISSUE TITLE
BBox2DList accepted types

### ISSUE THREAD

**Issue by mattans** [varunagrawal/bbox#14]
Hi,
`BBox2D` can accept a tuple, but `BBox2DList` can't accept a list of tuples.
Is it possible to make `BBox2DList` accept a list of tuples?
Maybe even let `BBox2D` accept and `typing.Sequence`, and `BBox2DList` any `Sequence` of `Sequence`s.

Thanks

**Comment by varunagrawal** [comment]
That should be straightforward. You could also potentially use a list comprehension to map the list of tuples to a list of `BBox2D`s and then pass that to the `BBox2DList`.
