### ISSUE TITLE
Try/except blocks should specify the exception

### ISSUE THREAD

**Issue by alkasm** [varunagrawal/bbox#5]
For e.g. at https://github.com/varunagrawal/bbox/blob/master/bbox/bbox2d_list.py#L223 (and a couple other blocks in that file, not sure if there are some in others), there is an exception block with no specified exception. That  will propagate an arbitrary exception forward as a value error, so if a user catches a value error from that they will be catching any possible exception. In other words, this is shadowing all exceptions as a ValueError.

**Comment by varunagrawal** [comment]
Ah good catch!

**Comment by varunagrawal** [comment]
Fixed.
