### ISSUE TITLE
Use __array__() method interface instead of numpy() method

### ISSUE THREAD

**Issue by alkasm** [varunagrawal/bbox#6]
Bounding boxes can be cast to a numpy array by exposing the `__array__` dunder method, so that you can call `np.array()` on it and get the result that you want instead of (or in addition to, so that you can still have the flag) the `numpy()` method.

https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.array.html

> object : *array_like*
>   > An array, any object exposing the array interface, an object whose \_\_array\_\_ method returns an array, or any (nested) sequence.

**Comment by varunagrawal** [comment]
What would the canonical representation be? Most datasets have the (xywh) format so I am leaning towards that, but if you have some evidence of which is preferred, I'll go with that.

**Comment by alkasm** [comment]
I'm not sure either, it's a good question and worth thinking on. The OpenCV
standard is x, y, w, h with the top left so maybe that would be useful from
a computational perspective. Maybe a list can be compiled of the NNs that
use the center vs the top left?

**Comment by varunagrawal** [comment]
I believe (x, y, w, h) is the preferred representation. It is common amongst datasets, and is used by popular models such as Faster-RCNN and Mask-RCNN. If you agree, I can implement that no problem.

Though now that I think about it, the `numpy()` method is just easier and less ambiguous. Pytorch follows the same API so I don't see why exposing the dunder method is even useful.

**Comment by varunagrawal** [comment]
I'm closing this since there has not been any updates and using the `numpy()` method is as easy as calling `np.array()`.
