### ISSUE TITLE
Publish updated package on PyPI to eliminate PIL dependency.

### ISSUE THREAD

**Issue by gmyers18** [varunagrawal/bbox#9]
The latest version on PyPI (0.8.3) includes a dependency on PIL in the utils module, but this is not reflected as a requirement in setup.py.  Would you consider publishing an updated version which includes fa838a0da where this explicit dependency was eliminated?

**Comment by varunagrawal** [comment]
Yeah that's a good point. I should just remove that method that imports PIL since it was for debugging and visualization mostly.

I should have the latest version published by this weekend. Apologies for the delay.

**Comment by varunagrawal** [comment]
Good news. Thanks to past-me doing some devops automation, the latest version with the `draw_cuboid` method removed has been published. Give it a go and let me know if this issue can be closed.

**Comment by gmyers18** [comment]
Looks good with 0.8.4.  Thanks for the quick fix!
